package com.armandroid.presupuesto.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "BUDGET".
 */
public class Budget implements Parcelable{

    private Long id;
    private Integer idUser;
    private String description;
    private String date;
    private float balance;
    private float money;
    private Expenses[] budgetExpenses;

    public Budget() {
    }

    public Budget(Parcel in){
        this.id = in.readLong();
        this.idUser = in.readInt();
        this.description = in.readString();
        this.date = in.readString();
        this.balance = in.readFloat();
        this.money = in.readFloat();
    }

    public Budget(Long id) {
        this.id = id;
    }

    public Budget(Long id, Integer idUser, String description, String date) {
        this.id = id;
        this.idUser = idUser;
        this.description = description;
        this.date = date;

    }

    public Budget(Long id, Integer idUser, String description, String date, float balance, float money) {
        this.id = id;
        this.idUser = idUser;
        this.description = description;
        this.date = date;
        this.balance = balance;
        this.money = money;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdUser() {
        return idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public float getBalance() {     return balance;   }
    public void setBalance(float balance) {       this.balance = balance;   }

    public float getMoney() {    return money;   }

    public void setMoney(float money) {        this.money = money;    }

    public Expenses[] getBudgetExpenses() {
        return budgetExpenses;
    }

    public void setBudgetExpenses(Expenses[] budgetExpenses) {
        this.budgetExpenses = budgetExpenses;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeInt(this.idUser);
        dest.writeString(this.description);
        dest.writeString(this.date);
        dest.writeFloat(this.balance);
        dest.writeFloat(this.money);
    }

    public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {
        public Budget createFromParcel(Parcel in) {
            return new Budget(in);
        }

        public Budget[] newArray(int size) {
            return new Budget[size];
        }
    };
}
