package com.armandroid.presupuesto.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MONEY_ENTRY".
 */
public class MoneyEntry {

    private Long id;
    private Integer idBudget;
    private Float mount;
    private String date;

    public MoneyEntry() {
    }

    public MoneyEntry(Long id) {
        this.id = id;
    }

    public MoneyEntry(Long id, Integer idBudget, Float mount, String date) {
        this.id = id;
        this.idBudget = idBudget;
        this.mount = mount;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdBudget() {
        return idBudget;
    }

    public void setIdBudget(Integer idBudget) {
        this.idBudget = idBudget;
    }

    public Float getMount() {
        return mount;
    }

    public void setMount(Float mount) {
        this.mount = mount;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
