package com.armandroid.presupuesto.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TDC".
 */
public class Tdc {

    private Long id;
    private String cardName;
    private Float credit;
    private Float expended;

    public Tdc() {
    }

    public Tdc(Long id) {
        this.id = id;
    }

    public Tdc(Long id, String cardName, Float credit, Float expended) {
        this.id = id;
        this.cardName = cardName;
        this.credit = credit;
        this.expended = expended;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCardName() {
        return cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    public Float getCredit() {
        return credit;
    }

    public void setCredit(Float credit) {
        this.credit = credit;
    }

    public Float getExpended() {
        return expended;
    }

    public void setExpended(Float expended) {
        this.expended = expended;
    }

}
