package com.armandroid.presupuesto.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "TDC".
 */
public class Tdc implements Parcelable{

    private Long id;
    private String cardName;
    private Float credit;
    private Float expended;

    public Tdc() {
        this.cardName = "";
        this.credit = 0f;
        this.expended = 0f;
    }

    public Tdc(Parcel in){
        this.id = in.readLong();
        this.cardName = in.readString();
        this.credit = in.readFloat();
        this.expended = in.readFloat();
    }

    public Tdc(Long id) {
        this.id = id;
    }

    public Tdc(Long id, String cardName, Float credit, Float expended) {
        this.id = id;
        this.cardName = cardName;
        this.credit = credit;
        this.expended = expended;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCardName() {
        return cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    public Float getCredit() {
        return credit;
    }

    public void setCredit(Float credit) {
        this.credit = credit;
    }

    public Float getExpended() {
        return expended;
    }

    public void setExpended(Float expended) {
        this.expended = expended;
    }

    @Override
    public String toString() {
        return cardName;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeString(this.cardName);
        dest.writeFloat(this.credit);
        dest.writeFloat(this.expended);
    }
    public static final Parcelable.Creator CREATOR = new Parcelable.Creator() {
        public Tdc createFromParcel(Parcel in) {
            return new Tdc(in);
        }

        public Tdc[] newArray(int size) {
            return new Tdc[size];
        }
    };
}
